### ISSUE TITLE
How to verify the VPA address using custom ui SDK - Flutter

### ISSUE THREAD

**Issue by yashwp** [razorpay/razorpay-flutter-customui#11]
I'm not able to find out a function to verify if the user's VPA is valid or not.

Can you guys redirect me to that function of this SDK?

**Comment by ramprasadAnand** [comment]
@yashwp this issue is been resolved, please update our razorpay_flutter_customui SDK to 1.1.0 to get this validation method.

**Comment by tanishqarora97** [comment]
@ramprasadAnand can you please provide any sample
